export const SHOW_LOADER = 'SHOW_LOADER';
export const SHOW_CONNECTION_ERROR = 'SHOW_CONNECTION_ERROR';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const SAVE_USER = 'SAVE_USER';
export const LOGOUT = 'LOGOUT';
export const PROFILE_SET_VALIDATION_ERR = 'PROFILE_SET_VALIDATION_ERR';
export const PROFILE_PREPARE_PAGE = 'PROFILE_PREPARE_PAGE';
export const PROFILE_EDIT_SUCCESS = 'PROFILE_EDIT_SUCCESS';

//Articles
export const ARTICLES_SAVE_TOTAL_PAGES = 'ARTICLES_SAVE_TOTAL_PAGES';

//Pagination Pages
export const PAGES_GET_PAGE_ARR = 'PAGES_GET_PAGE_ARR';
export const PAGES_SET_CURRENT_PAGE = 'PAGES_SET_CURRENT_PAGE';
export const PAGES_SHOW_NEXT_PAGES = 'PAGES_SHOW_NEXT_PAGES';
export const PAGES_SHOW_PREV_PAGES = 'PAGES_SHOW_PREV_PAGES';
