export const SHOW_LOADER = 'SHOW_LOADER';
export const SHOW_CONNECTION_ERROR = 'SHOW_CONNECTION_ERROR';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const SAVE_USER = 'SAVE_USER';
export const LOGOUT = 'LOGOUT';
export const PROFILE_SET_VALIDATION_ERR = 'PROFILE_SET_VALIDATION_ERR';
export const PROFILE_PREPARE_PAGE = 'PROFILE_PREPARE_PAGE';
export const PROFILE_EDIT_SUCCESS = 'PROFILE_EDIT_SUCCESS';

//Articles
export const ARTICLES_CLEAR_ARTICLES = 'ARTICLES_CLEAR_ARTICLES';
export const ARTICLES_SAVE_ARTICLES = 'ARTICLES_SAVE_ARTICLES';
export const ARTICLES_SAVE_TOTAL_PAGES = 'ARTICLES_SAVE_TOTAL_PAGES';
export const ARTICLES_SAVE_ARTICLE = 'ARTICLES_SAVE_ARTICLE';
export const ARTICLES_ARTICLE_FAVORITE_ACTION = 'ARTICLES_ARTICLE_FAVORITE_ACTION';
export const ARTICLES_ARTICLE_DELETE_ARTICLE = 'ARTICLES_ARTICLE_DELETE_ARTICLE';
export const ARTICLES_ARTICLE_UPDATE_ARTICLE = 'ARTICLES_ARTICLE_UPDATE_ARTICLE';
export const ARTICLES_NEW_ARTICLE_SET_VALIDATION_ERR = 'ARTICLES_NEW_ARTICLE_SET_VALIDATION_ERR';
export const ARTICLES_NEW_ARTICLE_SET_SLUG = 'ARTICLES_NEW_ARTICLE_SET_SLUG';
export const ARTICLES_NEW_ARTICLE_PREPARE_PAGE = 'ARTICLES_NEW_ARTICLE_PREPARE_PAGE';

//Pagination Pages
export const PAGES_GET_PAGE_ARR = 'PAGES_GET_PAGE_ARR';
export const PAGES_SET_CURRENT_PAGE = 'PAGES_SET_CURRENT_PAGE';
export const PAGES_SHOW_NEXT_PAGES = 'PAGES_SHOW_NEXT_PAGES';
export const PAGES_SHOW_PREV_PAGES = 'PAGES_SHOW_PREV_PAGES';

//Modal Window
export const MODAL_SET_VISIBLE = 'MODAL_SET_VISIBLE';
